findabl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

from . import settings
from places.urls import place_patterns
from users.views import toggle_mode_preference
from users.urls import user_patterns, registration_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('toggle_mode_preference/', toggle_mode_preference, name='toggle_mode_preference'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(place_patterns,namespace='places')),
    path('users/', include(user_patterns,namespace='users')),
    path('', include(registration_patterns, namespace='reg'))
)

places/urls.py
from django.urls import re_path, include, path

from places import views as place_views

place_patterns = ([
    path('', place_views.HomeView.as_view(), name='home'),
    path('<int:pk>/', place_views.PlaceDetailView.as_view(), name='place'),
    path('<int:pk>/rate/', place_views.ReviewCreateView.as_view(), name='rate'),
    path('<int:pk>/update/', place_views.ReviewUpdateView.as_view(), name='edit_review'),
    path('<int:pk>/delete/', place_views.ReviewDeleteView.as_view(), name='delete_review'),
    path('filter/', place_views.filter_search, name='filter_search'),
    path('about/', place_views.AboutView.as_view(), name='about'),
    path('search/', place_views.SearchResultsView.as_view(), name='search_results'),
], 'places')

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as user_views

user_patterns = ([
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', user_views.ActivateView.as_view(), name='activate'),
    path('contribution/', user_views.ContributionView.as_view(), name='contribution'),
    path('profile-delete/', user_views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile-delete-done/', user_views.ProfileDeleteDoneView.as_view(), name='profile_delete_done'),
], 'users')


registration_patterns = ([
    path('login/', user_views.CustomLoginView.as_view(), name='login'),
    path('logout/', user_views.CustomLogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html', success_url='/password-change-done/'), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html', success_url='/password-reset-done/', email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/password-reset-complete/'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

], 'registration')

places/models.py
from random import choice

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models import UniqueConstraint, QuerySet, Avg
from django.http import QueryDict
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _

DEFAULT_ORDER = 'score_avg'
MIN_SCORE = 1
MAX_SCORE = 5
CIRCLE_SCALE = 251
ScoreValidators = [MinValueValidator(MIN_SCORE), MaxValueValidator(MAX_SCORE)]

class PlaceQuerySet(QuerySet):

    def search(self, query_dict: QueryDict):
        qs = self
        q = query_dict.get('q', [None])
        q = q[0] # TODO: Full search
        if q:
            qs = qs.filter(name__icontains=q)
        qtypes = query_dict.get('type')
        if qtypes:
            qs = qs.filter(type__in=qtypes)

        qlocations = query_dict.get('location')
        if qlocations:
            qs = qs.filter(location__in=qlocations)
        
        qsort_option = query_dict.get('access', [None])[0]
        if qsort_option:
            qs = qs.order_by('score')
        return qs

class ReviewManager(models.Manager):

    def safe_get(self, user, place):
        """Custom `get` method for a `Review` model
        
        Like `get` method of a `Review` model, but returns `None` instead of raising a `DoesNotExist` error, when there are no matches in the database lookup"""

        qs = self
        try:
            qs = qs.get(user=user, place=place)
        except self.model.DoesNotExist:
            qs = None
        return qs


class Place(models.Model):

    ETH = "ETH"
    FAS = "FAS"
    # CAS = "CAS"
    FAM = "FAM"
    RES = "RES"
    CAF = "CAF"
    BAR = "BAR"
    OTH = "OTH"
    PIZ = "PIZ"

    TYPE_CHOICES = [
        (ETH, _('Ethnic')),
        (BAR, _('Bar')),
        (PIZ, _('Pizzeria')),
        (CAF, _('Café')),
        (FAS, _('Fast food')),
        (RES, _('Restaurant')),
        (FAM, _('Family-friendly')),
        (OTH, _('Other'))
    ]

    MOK = 'MOK'
    PPE = 'PRE'
    URW = 'URW'
    WOL = 'WOL'
    BIE = 'BIE'
    TAR = 'TAR'
    SRO = 'SRO'
    BEM = 'BEM'
    BIA = 'BIA'
    OCH = 'OCH'
    WAW = 'WAW'
    PPC = 'PPC'
    URS = 'URS'
    ZOL = 'ZOL'
    WLO = 'WLO'
    WIL = 'WIL'
    REM = 'REM'
    WES = 'WES'

    LOCATION_CHOICES = [
        (MOK, _('MOKOTÓW')),
        (PPE, _('PRAGA-POŁUDNIE')),
        (URW, _('URSYNÓW')),
        (WOL, _('WOLA')),
        (BIE, _('BIELANY')),
        (TAR, _('TARGÓWEK')),
        (SRO, _('ŚRÓDMIEŚCIE')),
        (BEM, _('BEMOWO')),
        (BIA, _('BIAŁOŁĘKA')),
        (OCH, _('OCHOTA')),
        (WAW, _('WAWER')),
        (PPC, _('PRAGA-PÓŁNOC')),
        (URS, _('URSYNÓW')),
        (ZOL, _('ŻOLIBORZ')),
        (WLO, _('WŁOCHY')),
        (WIL, _('WILANÓW')),
        (REM, _('REMBERTÓW')),
        (WES, _('WESOŁA'))
    ]

    name = models.CharField(_("Name"), max_length=240)
    location = models.CharField(_("Location"), max_length=4, choices=LOCATION_CHOICES)
    address = models.CharField(_("Address"), max_length=240)
    url =  models.URLField(_("Url on Google Maps"), unique=True)
    type = models.CharField(_("Type"), choices=TYPE_CHOICES, max_length=30, default=("OTH", _("Other")))
    objects = PlaceQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('places:place', kwargs={'pk': self.pk})

    def get_score(self, score_name: str) -> int:
        if not self.review_set.count():
            return None
        return self.review_set.aggregate(Avg(score_name))[score_name+'__avg']

    def get_review_scores(self):
        if not self.review_set.count():
            return []
        else:
            return [self.get_score(score_name[0]) for score_name in Review.SCORE_CATEGORY_CHOICES]

    def __str__(self):
        return self.name

class Review(models.Model):
    """ Represents a user review """
    SCORE_CATEGORY_CHOICES = [
        ('sin', _("Sensory intensity")),
        ('wac', _("Wheelchair accessibility")),
        ('noi', _("Quiet")),
        ('lsi', _("Low-sight friendliness"))
    ]
    SCORE_CHOICES = [(i,i) for i in range(MIN_SCORE, MAX_SCORE)]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    place = models.ForeignKey(Place, verbose_name=_("Place"), on_delete=models.CASCADE)
    creation_date = models.DateTimeField(_("Creation date"), auto_now_add=True)
    # score_avg = models.FloatField(_("Average rating"), default=0)
    sin = models.IntegerField(_("Sensory intensity"), choices=SCORE_CHOICES, blank=False, default=1, validators=ScoreValidators)
    wac = models.IntegerField(_("Wheelchair accessibility"), choices=SCORE_CHOICES, blank=False, default=1, validators=ScoreValidators)
    noi = models.IntegerField(_("Noise"), choices=SCORE_CHOICES, blank=False, default=1, validators=ScoreValidators)
    lsi = models.IntegerField(_("Low-sight friendly"), choices=SCORE_CHOICES, blank=False, default=1, validators=ScoreValidators)
    objects = ReviewManager()

    def get_score_circle_scale(score):
        return (1 - score / (MAX_SCORE)) * CIRCLE_SCALE
    
    def get_score_color_value(score):
        return 255 - score * 255 / MAX_SCORE
        
    
    class Meta:
       constraints = [
			UniqueConstraint(fields=['user', 'place'], name=_('One review per place'))
		]

    def __str__(self):
        return "{0}: {1}".format(self.user.id, self.place.name)

# class City

places/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Review, Place#, ACCESS_CHOICES
from django.conf import settings

class AdvancedSearchForm1(forms.Form):
    location = forms.MultipleChoiceField(
        choices=Place.LOCATION_CHOICES,
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': "search-form-checkbox"}
        ),
        localize=True
        )

class AdvancedSearchForm2(forms.Form):
    type = forms.MultipleChoiceField(
        choices=Place.TYPE_CHOICES,
        required=False,
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': "search-form-checkbox"}
        ),
        localize=True
        )

class AdvancedSearchForm3(forms.Form):
    access = forms.MultipleChoiceField(
        choices=Review.SCORE_CATEGORY_CHOICES,
        required=False,
        widget=forms.RadioSelect(
            attrs={'class': "search-form-checkbox"}
        ),
        localize=True
        )

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review 
        fields = [ i[0] for i in model.SCORE_CATEGORY_CHOICES]
        localized_fields = '__all__'
        # required_fields = 
        widgets = {f: forms.RadioSelect(
            attrs={
                'class': "radio-field",
            },
        ) for f in fields}

places/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import F, Avg
from django.views.generic import TemplateView, DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from ratelimit.decorators import ratelimit

from .models import Place, Review, MIN_SCORE, MAX_SCORE
from .forms import AdvancedSearchForm1, AdvancedSearchForm2, AdvancedSearchForm3, ReviewForm

NAME_DICTS = {
        ('location', 'Location'): dict(Place.LOCATION_CHOICES),
        ('type', 'Type'): dict(Place.TYPE_CHOICES),
        ('access', 'Accessibility'): dict(Review.SCORE_CATEGORY_CHOICES)
    }

class PlaceDetailView(DetailView):
    """Displays the details about an instance of the `place` model"""

    model = Place
    template_name = 'places/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['max_score'] = MAX_SCORE
        context['min_score'] = MIN_SCORE
        review_count = self.object.review_set.count()
        context['review_count'] = review_count
        review_scores = self.object.get_review_scores()
        if review_count:
            context['scores'] = [{
                'circle_scale': Review.get_score_circle_scale(sc),
                'name': name[0],
                'verbose_name': name[1],
                'value': sc,
                'score_color': Review.get_score_color_value(sc)
                } for (name,sc) in zip(Review.SCORE_CATEGORY_CHOICES + [('score_avg', _('Average'))], review_scores + [sum(review_scores) / len(review_scores)])]    # get scores' context
        if self.request.user.is_authenticated:
            context['review'] = Review.objects.safe_get(user=self.request.user, place=self.object)    # get current user's review
        return context

class SearchResultsView(ListView):
    """Displays search results"""

    model = Place
    filter_options = NAME_DICTS.keys()
    template_name = 'places/search_results.html'
    paginate_by = 5

    def get_queryset(self):
        if not self.request.session.get('filter-results'):
            self.q = dict(self.request.GET.lists())
        else:
            self.request.session['filter-results'] = False
            self.q = self.request.session.get('q', {})
        main_score_name = self.q.get('access', [None])[0]
        if main_score_name:
            main_score = Avg('review__' + main_score_name)
        else:
            main_score = sum(Avg('review__'+score_name[0]) for score_name in Review.SCORE_CATEGORY_CHOICES) / len(Review.SCORE_CATEGORY_CHOICES)
        place_list = Place.objects.annotate(score=main_score).search(self.q)
        return place_list.annotate(
            score_circle_scale=Review.get_score_circle_scale(F('score')),
            score_color=Review.get_score_color_value(F('score'))
            )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name_dicts"] = NAME_DICTS
        context["filters"] = self.filter_options
        context["queries"] = self.q if self.q else dict(self.request.GET.lists())
        return context

    def __init__(self, q=None, **kwargs) -> None:
        self.q = q
        super().__init__(**kwargs)

def filter_search(request):
    """Displays filter form"""

    forms = [
        (AdvancedSearchForm1, {'location' : request.session.get('location', None)}),
        (AdvancedSearchForm2, {'type' : request.session.get('type', None)}),
        (AdvancedSearchForm3, {'access' : request.session.get('access', None)})

    ]
    request.session['filter-results'] = False
    steps = len(forms)
    step = int(request.GET.get('goto_step', int(request.GET.get('step', 0))+1))
    template = 'places/generic_search_form.html'
    queries =  {key: list(set(vals)) for key, vals in request.GET.lists() if key in (key[0] for key in NAME_DICTS.keys())}
    # request.session['q'] = {}
    if not request.session.get('q', None): request.session['q'] = {}
    request.session['q'].update(queries)
    if step-1==steps:
        request.session['filter-results'] = True
        return SearchResultsView.as_view()(request, q=request.session['q'])
    context = {
        'form': forms[step-1][0](initial=forms[step-1][1], auto_id=False),
        'step': step,
        # 'queries': queries,
        'steps': {
            'step':step, 
            'count':steps, 
            'prev': max(step-1, 0)
            }
        }
    return render(request, template, context)

class HomeView(TemplateView):
    template_name = 'home.html'

class AboutView(TemplateView):
    template_name = 'about.html'

@method_decorator(ratelimit(key='ip', rate='10/m', method='POST'), name='post')
class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'places/review_create_form.html'
    form_class = ReviewForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.place = get_object_or_404(Place, id=self.kwargs['pk'])
        r = super().form_valid(form)
        return r

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['review'] = {'place':get_object_or_404(Place, id=self.kwargs['pk'])}
        return context

    def get_success_url(self):
        return (reverse_lazy('places:place', args=(self.kwargs['pk'],)))

class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    """deletes a ``Review`` instance."""

    model = Review
    template_name = 'places/review_confirm_delete.html'

    def get_object(self):
        return Review.objects.get(user=self.request.user, place=get_object_or_404(Place, id=self.kwargs['pk']))

    def get_success_url(self):
        return (reverse_lazy('places:place', args=(self.kwargs['pk'],)))
        
class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    """updates a ``Review`` instance."""

    model = Review
    template_name = 'places/review_create_form.html'
    form_class = ReviewForm

    def get_object(self, queryset):
        return Review.objects.get(user=self.request.user, place=get_object_or_404(Place, id=self.kwargs['pk']))

    def get_success_url(self):
        return (reverse_lazy('places:place', args=(self.kwargs['pk'],)))

places/templates/places/detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ place.name }} - Findabl{% endblock %}

{% block content %}
<section class="col main-section">
	{% if '/search/' in request.META.HTTP_REFERER %}
	<div class="row left-adjusted">
		<span class="material-symbols-outlined">arrow_back</span>
		<a href="{{ request.META.HTTP_REFERER }}">
		{% translate "Back to search results" %}</a>
	</div>
	{% endif %}
	<h2>
		<strong>{{ place.name }}</strong>
	</h2>
	<div class="col details">
		<div class="row">
		<div class="col labels">
			<div class=""><span class="material-symbols-outlined">label</span>{{ place.get_type_display }}</div>
				<div><span class="material-symbols-outlined">location_on</span>
				{{ place.get_location_display|title }}
				</div>
				<div class="">
					<span class="material-symbols-outlined">output</span>
					<a href="{{ place.url }}" class="">{% translate "See this place on Google Maps" %}</a>
				</div>
		</div>
		<div class="col">
			{% if not review_count %}
			<p class="faded">No reviews yet.</p>
			{% else %}
				{% with score=scores|last %}
				{% include 'places/score_circle.html' %} 
				{% endwith %}
			{% endif %}
			{% if user.is_authenticated %}
			{% if not review %}
			<a href="{% url 'places:rate' place.pk %}" class="btn primary">{% translate 'Review this place' %}</a>
			{% else %}
			<a href="{% url 'places:edit_review' place.pk %}" class="btn primary">{% translate 'Edit your review' %}</a>
			{% endif %}
			{% endif %}
		</div>
		</div>
	</div>
	{% block ratings %}
	<section class="labels">
		<h3><strong>{% translate "Customer reviews" %}</strong></h3>
		{% if not review_count %}
		<p class="faded">{% translate 'No reviews yet.' %}</p>
		{% else %}
		<p>
			{% blocktranslate with c=1 count counter=review_count %}
			1 review
			{% plural %}
			{{ counter }} reviews
			{% endblocktranslate %} 
		</p>
		{% with score_set=scores %}
		{% include 'places/scores.html' %}
		{% endwith %}
		<p><a href="{% url 'places:about' %}#features">{% translate 'Learn more about these ratings' %}.</a></p>
		{% endif %}
	</section>
	{% endblock %}
	<section class="">
		<h3><strong>{% translate "Photos" %}</strong></h3>	
		<ul class="gallery">
			{% for photo in place.photos %}
			<li>
				<figure class="">
					<img src="{{ photo.url }}" alt="{{ photo.alt }}">
				</figure>
			</li>
			{% empty %}
			<p class="faded">{% translate 'No photos here' %}.</p>
			{% endfor %}
		</ul>
	</section>
	<section class="col map">
		<h3>{% translate 'This place on map' %}</h3>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2443.8061281194214!2d21.016505000000002!3d52.228739999999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471eccf17a777be9%3A0xe2cc085bd5661c5c!2sTrattoria%20Da%20Antonio!5e0!3m2!1sen!2spl!4v1663448976503!5m2!1sen!2spl"
			allowfullscreen="" 
			loading="lazy" 
			referrerpolicy="no-referrer-when-downgrade">
		</iframe>
	</section>
</section>
{% endblock %}

places/templates/places/generic_search_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}

<form class="col form-block" action="/filter/" method="get">
  <p>Step {{ steps.step }} of {{ steps.count }}</p>
  {% if not steps.step == steps.count %}
  <!-- something -->
  {% endif %}
    <input type="hidden" name="step" value="{{ step }}">
    {% for field in form %}
      <div class="fieldWrapper">
        {{ field.errors }}
        <h3>{{ field.label_tag }} </h3>
        {% if field.widget_type == 'checkbox' %}
          <input name="select-all" type="checkbox" onclick="toggleCheckboxes(this, event);" />{% translate 'Select all' %}<br/>
        {% endif %}
      {{ field }}
      {% if field.help_text %}
      <p class="help">{{ field.help_text|safe }}</p>
      {% endif %}
    </div>
  {% endfor %}

{% for key, vals in queries %}
  {% for val in vals %}
    {% if not key == 'step' %}
      <!-- <input type="hidden" name="{{ key }}" value="{{ val }}"> -->
    {% endif %}
  {% endfor %}
{% endfor %}

  {% if steps.prev %}
  <!-- <button name="goto_step" type="submit" value="{{ steps.first }}">{% trans "first step" %}</button> -->
  <button class="btn secondary" name="goto_step" type="submit" value="{{ steps.prev }}">{% translate "Back" %}</button>
  {% endif %}
    <!-- <input type="button" class="btn btn-inv" value="{% translate 'Go back' %}"> -->
  {% if steps.next %}
  {% endif %}
  <input type="submit" class="btn primary" value="{% translate 'Next' %}">
</form>

<noscript>
  <style>
    .select-all {display:none;}
    </style>
</noscript>
<script src="{% static 'places/js/toggleSelectAllBtn.js' %}">
</script>

{% endblock %}

places/templates/places/review_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>
        {% translate 'Are you sure you want to delete your review of ' %}<a href="{% url 'places:place' view.kwargs.pk %}">{{ object.place.name }}</a>?
    </p>
    <p class="row row-buttons">
        <a href="{% url 'places:place' view.kwargs.pk %}">{% translate 'Cancel' %}</a>
        <input type="submit" class="btn" value="{% translate 'Confirm' %}">
    </p>
</form>
{% endblock %}

places/templates/places/review_create_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<section class="main-section">
	<h2><strong>{% translate 'Review of ' %}<a href="{% url 'places:place' view.kwargs.pk %}">{{ review.place.name }}</a></strong></h2>
	<p>
		{% translate 'Read about creating reviews' %} <a href="{% url 'places:about' %}#reviews">{% translate ' here.' %}</a>
	</p>
	<form method="post" class="col form-block">
		{% csrf_token %}
		
		{% for field in form %}
		<!-- <div class=""> -->
			{{ field.label_tag }}<br>
			{{ field }}
			{% if field.help_text %}
			  <p class="help">{{ field.help_text|safe }}</p>
			{% endif %}
			{% for error in field.errors %}
			  <p class="danger-text">{{ error }}</p>
			{% endfor %}
		<!-- </div> -->
		{% endfor %}
		
	
		<div class="row row-buttons">
			<a class="" href="{% url 'places:place' view.kwargs.pk %}" >{% translate 'Cancel' %}</a>
			{% if object %}
			<a class="danger-text" href="{% url 'places:delete_review' object.place.pk %}">{% translate 'Delete review' %}</a>
			{% endif %}
			<input type="submit" value="{% translate 'Save review' %}" class="btn">
		</div>
	</form>
{% endblock %}

places/templates/places/score_circle.html
<p class="rating-num">
    <svg class="rating-circle" stroke-dashoffset="{{ score.circle_scale }}">
        <!-- <circle class="background-circle" stroke="grey"/> -->
        <circle stroke="rgba({{ score.score_color }}, 228, 0, 0.59)"/>
        <text text-anchor="middle" dominant-baseline="central">
            {{ score.value|floatformat:1 }}
        </text>
    </svg>
</p>

places/templates/places/scores.html
{% load i18n %}

<div class="row ratings">
    {% for score in score_set %}
    {% if not score.name == "score_avg" %}
    <div class="col">
        <h4 class="">{{ score.verbose_name }}</h4>
        <p class="rating-num">
            <svg class="rating-circle-sm" stroke-dashoffset="{{ score.circle_scale }}">
                <!-- <circle class="background-circle" stroke="grey"/> -->
                <circle stroke="rgba({{ score.score_color }}, 228, 0, 0.59)"/>
                <text text-anchor="middle" dominant-baseline="central">{{ score.value|floatformat:1 }}</text>
            </svg> 
        </p>
    </div>
    {% endif %}
    {% endfor %}
</div>

places/templates/places/search_form.html
{% load i18n %}

<form method="get" class="row form-inline" action="{% url 'places:search_results' %}" name="search-form">
    <input type="search" name="q" class="input">
        <button type="submit" class="btn btn-search secondary">{% translate "Search" %}</button>
    </div>
</form>

places/templates/places/search_results.html
{% extends 'base.html' %}

{% load i18n %}
{% load place_extras %}
{% block content %}

<section class="col main-section">
	<h2>{% translate 'Results for:' %}</h2>
	<div class="left-adjusted">
			<ul>
				{% for key in filters %}
				<li>
					{{ key.1 }}:
					<section class="row queries">
					{% for val in queries|lookup:key.0 %}
						<div class="btn secondary query">
							{{ name_dicts|lookup:key|lookup:val|title }}
						</div>
					{% empty %}
					<div class="btn secondary query">All</div>
					{% endfor %}
					</section>
				</li>
				{% endfor %}
			</ul>
			<a href="{% url 'places:filter_search' %}">{% translate 'Change search options' %}</a>
	</div>
	{% if object_list %}
	<ul class="col">
	{% for place in object_list %}
		<li class="card">
			<h3>{{ place.name }}</h3>
			<div class="row">
			<div class="labels">
				<div class="">
					<span class="material-symbols-outlined">label</span>{{ place.get_type_display }}
				</div>
				<div><span class="material-symbols-outlined">location_on</span>
					{{ place.get_location_display|title }}
				</div>
				<div class="">
					<span class="material-symbols-outlined">output</span>
					<a href="{{ place.url }}" class="">{% translate "See this place on Google Maps" %}</a>
				</div>
			</div>
			<div class="">
				{% if not place.review_set.count == 0 %}
				<p class="rating-num">
					<svg class="rating-circle" stroke-dashoffset="{{ place.score_circle_scale }}">
						<circle stroke="rgba({{ place.score_color }}, 228, 0, 0.59)"/>
						<text text-anchor="middle" dominant-baseline="central">{{ place.score|floatformat:1 }}</text>
					</svg> 
				</p>
				{% else %}
				<p class="faded">{% translate 'No reviews' %}</p>
				{% endif %}
				<a href="{% url 'places:place' place.id %}" class="btn primary btn--small">{% translate "See details" %}</a>
			</div>
			</div>
		</li>
	{% endfor %}
	</ul>
	{% if is_paginated %}
	<hr>
	<nav aria-label="Places navigation">
		<ul class="pagination">
			{% if page_obj.has_previous %}
				<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
				</li>
			{% else %}
				<li class="page-item disabled">
						<a class="page-link" href="#" tabindex="-1">Previous</a>
				</li>
			{% endif %}
			{% for i in paginator.page_range %}
				{% if page_obj.number == i %}
					<li class="page-item active">
						<a class="page-link" href="?page={{ i }}">
							<span>{{ i }}<span class="sr-only">(current)</span></span>
						</a>
					</li>
				{% else %}
					<li class="page-item">
						<a class="page-link" href="?page={{ i }}">
							<span>{{ i }}</span>
						</a>
					</li>
				{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
				<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#">Next</a>
				</li>
			{% endif %}
		</ul>
	</nav>
	{% endif %}
	{% else %}
	<p class="">{% translate "Couldn't find places with these parameters. Try a different search or use our filter." %}
	</p>
	<a href="{% url 'places:filter_search' %}" class="btn primary">{% translate 'Browse' %}</a>
	{% endif %}
</section>
{% endblock %}