findabl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

from . import settings
from places.urls import place_patterns
from users.views import toggle_mode_preference
from users.urls import user_patterns, registration_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('toggle_mode_preference/', toggle_mode_preference, name='toggle_mode_preference'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(place_patterns,namespace='places')),
    path('users/', include(user_patterns,namespace='users')),
    path('', include(registration_patterns, namespace='reg'))
)

places/urls.py
from django.urls import re_path, include, path

from places import views as place_views

place_patterns = ([
    path('', place_views.HomeView.as_view(), name='home'),
    path('<int:pk>/', place_views.PlaceDetailView.as_view(), name='place'),
    path('<int:pk>/rate/', place_views.ReviewCreateView.as_view(), name='rate'),
    path('<int:pk>/update/', place_views.ReviewUpdateView.as_view(), name='edit_review'),
    path('<int:pk>/delete/', place_views.ReviewDeleteView.as_view(), name='delete_review'),
    path('filter/', place_views.filter_search, name='filter_search'),
    path('about/', place_views.AboutView.as_view(), name='about'),
    path('search/', place_views.SearchResultsView.as_view(), name='search_results'),
], 'places')

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views as user_views

user_patterns = ([
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', user_views.ActivateView.as_view(), name='activate'),
    path('contribution/', user_views.ContributionView.as_view(), name='contribution'),
    path('profile-delete/', user_views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile-delete-done/', user_views.ProfileDeleteDoneView.as_view(), name='profile_delete_done'),
], 'users')


registration_patterns = ([
    path('login/', user_views.CustomLoginView.as_view(), name='login'),
    path('logout/', user_views.CustomLogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html', success_url='/password-change-done/'), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html', success_url='/password-reset-done/', email_template_name='users/password_reset_email.html'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/password-reset-complete/'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

], 'registration')

users/models.py
# from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
# Create your models here.
# class User(AbstractUser):
# 	pass

class Preferences(models.Model):
    
    themes = (
        ('light', 'Light Theme'),
        ('dark', 'Dark Theme'),
    )
    
    preference_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    theme = models.CharField(max_length=255, choices=themes)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError
from django import forms

class RegistrationForm(UserCreationForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['email'].required = True
#         self.fields['username'].error_messages = {'invalid': 'foobar'}
    email = forms.EmailField(required=True)
    # first_name = forms.CharField(label="")
    def clean(self):
       email = self.cleaned_data.get('email')
       if User.objects.filter(email=email).exists():
            raise ValidationError("User with provided email already exists. To register a new account, use a unique email address.")
       return self.cleaned_data
    class Meta:
        model = User
        fields = ('first_name', 'username', 'email', 'password1', 'password2', )

users/views.py
# from re import template
from django.shortcuts import render
#from rest_framework import viewsets
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
#from .serializers import UserSerializer
# To make password encryption
# from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, HttpResponse
from users.models import Preferences
from django.views.generic import View, FormView, TemplateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from users.forms import RegistrationForm
from django.template.loader import render_to_string
# from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.db import models
from users.tokens import email_verification_token
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from django.utils.decorators import method_decorator
from ratelimit.decorators import ratelimit
# from django.db.models import Model
from django.contrib import messages
from django.contrib.auth import views as auth_views
from users.models import Profile

MANUAL_VERIFICATION = False
EMAIL_VERIFICATION = True

# class ProfileView(LoginRequiredMixin, TemplateView):
#     template_name = 'users/profile.html'

@method_decorator(ratelimit(key='ip', rate='3/m', method='POST'), name='post')
class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = RegistrationForm
    # success_url = '/users/success/'

    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'users/already_logged_in.html')
        return super().get(self, request)

    def form_valid(self, form):
        self.request.session['activation-required'] = True
        user = form.save(commit=False)
        if EMAIL_VERIFICATION:
            user.is_active = False
            self._send_email_verification(user)
        user.save()
        #handle errors
        return render(self.request, 'registration/registration_done.html')
    
    def _send_email_verification(self, user: User):
        current_site = get_current_site(self.request)
        subject, to = 'Activate Your Account', user.email
        context = {
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': email_verification_token.make_token(user),
            }
        html_content = render_to_string(
            'registration/email_verification.html',
            context=context
            )
        text_content = strip_tags(html_content)
        msg = EmailMultiAlternatives(subject, text_content, to=[to])
        msg.attach_alternative(html_content, "text/html")
        msg.content_subtype = "html"
        if not msg.send():
            if not user.is_active: get_user_model().objects.get(pk=user.pk).delete()
            messages.error(self.request, f'Problem sending confirmation email to {to}, check if you typed it correctly.')

class ActivateView(View):
    def get_user_from_email_verification_token(self, uidb64: str, token: str):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = get_user_model().objects.get(pk=uid)
        except (ValueError, OverflowError, get_user_model().DoesNotExist):
            return None
        if user is not None and email_verification_token.check_token(user, token):
            return user
        return None
    
    def get(self, request, uidb64, token):
        user = self.get_user_from_email_verification_token(uidb64, token)
        if not user:
            return HttpResponse('The activation was not successful. Get a new activation link or check if your account is already activated.')
        # if MANUAL_VERIFICATION:
        # TODO
        user.is_active = True
        user.save()
        return render(request, "registration_complete.html")

class CustomLoginView(auth_views.LoginView):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'users/already_logged_in.html')
        return super().get(self, request)

class CustomLogoutView(auth_views.LogoutView):
    next_page = None
    # template_name = 'users/templates/registration/logged_out.html'

def toggle_mode_preference(request, *args, **kwargs):
    toggle = {"light":"dark", "dark":"light"}
    if request.user.is_authenticated:
        try:
            pref = Preferences.objects.get(user=request.user)
            pref.theme = toggle[(pref.theme)]
            pref.save(update_fields=["theme"])
        except Preferences.DoesNotExist:
            theme = toggle[request.session.get('theme','light')]
            Preferences.objects.create(user=request.user, theme=theme)
    else:
        request.session['theme'] = toggle[request.session.get('theme','light')]
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    # login_url = '/login/'
    """View to delete a ``Profile`` instance."""
    model = Profile
    template_name = 'users/profile_confirm_delete.html'
    success_url = '/users/profile-delete-done/'
    def get_object(self, queryset = ...) -> models.Model:
        return self.request.user

class ProfileDeleteDoneView(TemplateView):
    template_name = 'users/profile_delete_done.html'

class ProfileUpdateView(UpdateView):
    """View to delete a ``Profile`` instance."""
    model = Profile
    template_name = 'users/profile_update.html'
    #success_url = '/'
    # form_class = ProfileUpdateForm
    def form_valid(self, form):
        # update user
        return super().form_valid(form)

class ContributionView(TemplateView):
    template_name = 'users/contribution.html'

users/templates/users/already_logged_in.html
{% extends "base.html" %}

{% block content %}

<p>{% translate 'You're already logged in' %}.</p>
{% include 'registration/logout.html' %}

{% endblock %}

users/templates/users/contribution.html
{% extends 'base.html' %}

{% load i18n %} 
{% block content %}
<section class="main-section">
    <h2 class="left-adjusted">
        {% if request.user.is_authenticated %}
        {% translate 'Hi' %}, {{ user.username }}
        <br>
        {% endif %}
        {% translate "Here is how you can contribute" %}
    </h2>
    <p>
    </p>
    <ul>
        <li>{% blocktranslate %}
            Share errors and suggestions on <a href="https://github.com/mboiar/findabl">our Github</a>.
        </li>{% endblocktranslate %}
        <li>
            <p>{% translate 'Help to expand the project by reviewing visited places.' %}</p>
            {% if request.user.is_authenticated %}
            <h3>{% translate 'Your reviews' %}</h3>
            <ul class="">
            {% for review in request.user.review_set.all %}
                <li class="row">
                    <h4>{{ review.place.name }}</h4>
                    <a href="{% url 'places:edit_review' review.pk %}" class="btn btn--small">{% translate 'Edit review' %}</a>
                </li>
            {% empty %}
            <li><p>{% translate 'You do not have any reviews yet' %}.</p></li>
            {% endfor %}
            </ul>
            <a href="{% url 'reg:logout' %}">{% translate 'Logout' %}</a>
            <a href="{% url 'reg:password_change' %}" >{% translate 'Change password' %}</a>
            <a href="{% url 'users:profile_delete' %}" class="danger-text">{% translate 'Delete account' %}</a>
            {% else %}
            <p>
                <a class="" href="{% url 'reg:login' %}">{% translate 'Log in' %}</a>{% translate ' or ' %} <a class="" href="{% url 'users:register' %}">{% translate 'register' %}</a>{% translate ' to create or edit reviews.' %}
            </p>
            {% endif %}
        </li>
    </ul>
</section>
{% endblock %}

users/templates/users/logged_out.html
{% extends "base.html" %}

{% block content %}

<p>{% translate 'You're successfully logged out' %}.</p>
<p><a href="{% url 'reg:login' %}">{% translate 'Log in' %}</a>{% translate ' or ' %}<a href="{% url 'places:home' %}">{% translate 'Go Home' %}</a></p>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %} 

{% load i18n %}

{% block content %}
<p>{% translate 'Password changed successfully' %}.</p>
<p><a href="{% url 'places:home' %}">{% translate 'Go Home' %}</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>{% translate 'Change password' %}</h2>
<form method="post">
{% csrf_token %}
{% for e in form.errors %}
<p>{{ e }}</p>
{% endfor %}
<ul>
    {% for field in form %}
    <li>{{ field.label }} {{ field }}</li>

    {% endfor %}
</ul>

<input class='btn' type="submit" value="{% translate 'Save changes' %}">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %} 

{% load i18n %}

{% block content %}
<p>{% translate 'The password has been successfully reset' %}.</p>
<p><a href="{% url 'places:home' %}">{% translate 'Go Home' %}</a></p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}

<form method="post">
{% csrf_token %}

{{ form }}

<input class='btn' type="submit" value="{% translate 'Confirm new password' %}">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %} 

{% load i18n %}

{% block content %}
<p>{% translate 'Request for password reset accepted. Follow the instructions sent to your email to complete reset' %}.</p>
<p><a href="{% url 'places:home' %}">{% translate 'Go Home' %}</a></p>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
2 	{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
3 	
4 	{% translate "Please go to the following page and choose a new password:" %}
5 	{% block reset_link %}
6 	{{ protocol }}://{{ domain }}{% url 'reg:password_reset_confirm' uidb64=uid token=token %}
7 	{% endblock %}
8 	{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
9 	
10 	{% translate "Thanks for using our site!" %}
11 	
12 	{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
13 	
14 	{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}

<h2>Password reset</h2>
<form method="post">
{% csrf_token %}
{{ form }}
<input class='btn' type="submit" value="{% translate 'Reset' %}">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %} 

{% load i18n %}

{% block content %}
<section class="profile-info">
<h2>{% translate 'Hi' %}, {{ user.username }}</h2>
<div>
<img src="#" caption="Profile Photo">
</div>
<a href="#" >{% translate 'Edit profile' %}</a>
<a href="{% url 'reg:password_change' %}" >{% translate 'Change password' %}</a>
{% include 'registration/logout.html' %}
<a href="#" >{% translate 'Delete account' %}</a>
</section>
<section class="user-reviewed-places">
    <ul>
    {% for review in reviews %}
        <li>
            <div class="place">

            </div>
        </li>
    {% empty %} 
    <p>{% translate 'Reviewed places will appear here' %}</p>
    {% endfor %}
</ul>
</section>
{% endblock %}

users/templates/users/profile_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <p>
        {% translate 'Are you sure you want to delete your account?' %}
    </p>
    <p class="row row-buttons">
        <a href="{% url 'users:contribution' %}">{% translate 'Cancel' %}</a>
        <input type="submit" class="btn" value="{% translate 'Confirm' %}">
    </p>
</form>

{% endblock %}

users/templates/users/profile_delete_done.html
{% extends 'base.html' %} 

{% load i18n %}

{% block content %}

<p>{% translate 'Your profile has been successfully deleted' %}.</p>
<p><a href="{% url 'places:home' %}">{% translate 'Go Home' %}</a></p>

{% endblock %}

users/templates/users/profile_update.html
{% load i18n %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="{% translate 'Save changes' %}">
</form>